# Generated by Django 2.2.16 on 2022-06-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220615_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='mxnqqdmbnc', max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
