# Generated by Django 2.2.16 on 2022-06-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20220616_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='qvhvwvkzwk', max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
