# Generated by Django 2.2.16 on 2022-06-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20220616_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='kcjgjnoewd', max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
