# Generated by Django 2.2.16 on 2022-06-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20220616_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title_id',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='digcdnxrrg', max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
