# Generated by Django 2.2.16 on 2022-06-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20220616_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('category',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='ybwsmaxnmd', max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
