# Generated by Django 2.2.16 on 2022-06-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_auto_20220617_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('review_id',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='yzqopdlhno', max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
