# Generated by Django 2.2.16 on 2022-06-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_auto_20220617_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='kdputjbwcq', max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
