# Generated by Django 2.2.16 on 2022-06-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_auto_20220617_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='yyivisgfgz', max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
