# Generated by Django 2.2.16 on 2022-06-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0023_auto_20220620_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='ntnsvjgynu', max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
