# Generated by Django 2.2.16 on 2022-06-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0025_auto_20220621_0924'),
        ('reviews', '0025_auto_20220621_0052'),
    ]

    operations = [
    ]
